@startuml


package Model{
    class Image{
        url: String
    }

    class Animation{
        frames: List<Image>
        duration: Int
    }

    class User {
        - pet: Pet
    }

    class Mood{
        - title: String
        - description: String
    }

    class Pet {
        + name: String
        + animation: Animation?
        + image: Image
        - mood: Mood
    }

    enum Priority {
        NORMAL
        HIGH
    }

    class Goal {
        + name: String
        + priority: Priority
        + isDone: Boolean
    }

    Goal *- Priority
    User *-- Pet
    User *.. Goal: "indirectly"
    Pet o-- Image
    Pet o-- Animation
    Pet o-- Mood
    Animation o-- Image
}

package View{
    class SignupView{
    }

    class HomeView {
    }

    class SettingsView{
    }
}

package ViewModel{
    class SignupViewModel{
        login()
        user: User
        pets: List<Pet>
    }
    class HomeViewModel {
        addGoal()
        markGoalDone()
        user: User
    }
    class SettingsViewModel{
        userSettings: UserSettings
        saveSettings()
    }
}

package Repository{
    class UserRepository {
        getUser()
        saveUser()
    }

    class GoalRepository {
        getGoals()
        saveGoal()
        updateGoal()
    }
}
package DAO{
    class UserDAO


    class GoalDAO
}

class AppConfig{
    pets: List<Pet>
}

AppConfig o-- Pet
SignupView .down.> SignupViewModel
HomeView .down.> HomeViewModel
SettingsView .down.> SettingsViewModel


HomeViewModel .down> GoalRepository
HomeViewModel .down> UserRepository
SignupViewModel .down> UserRepository
SettingsViewModel .down.> UserRepository


UserRepository ..down> UserDAO
GoalRepository ..down> GoalDAO
GoalRepository ..> Pet: "updates"

UserDAO -down-> User
GoalDAO -down-> Goal
@enduml
