@startuml


package Model{

    class Image{
        url: String
    }

    class Animation{
        frames: List<Image>
        duration: Int
    }
    class User {
        - pet: Pet
    }
    class UserSettings{
        + petName: String
        + reminders: Boolean
    }

    class Pet {
        - id: Int
        + name: String
        + animation: Animation?
        + image: Image
    }
    enum Priority {
        LOW
        MEDIUM
        HIGH
    }

    class Goal {
        + name: String
        + deadline: Date?
        + priority: Priority
        + createdAt: Date
        + doneAt: Date?
        + isDone(): Boolean
        + markAsDone()
    }
    Goal o- Priority
    User *-- Pet
    User *-- Goal
    User *-- UserSettings
    Pet o-- Image
    Pet o-- Animation
    Animation o-- Image

}

package View{
    class InitialLoginView{
    }

    class HomeView {
    }

    class SettingsView{
    }
}

package ViewModel{
    class InitialLoginViewModel{
        login()
        user: User
        pets: List<Pet>
    }
    class HomeViewModel {
        addGoal()
        markGoalDone()
        user: User
    }
    class SettingsViewModel{
        userSettings: UserSettings
        saveSettings()
    }
}

package Repository{
    class UserRepository {
        getUser()
        saveUser()
    }
    class PetRepository{
        getAll()
    }

    class GoalRepository {
        getGoals()
        saveGoal()
        updateGoal()
    }
}
package DAO{
    class UserDAO

    class PetDAO

    class GoalDAO
}

InitialLoginView -down-> InitialLoginViewModel
HomeView -down-> HomeViewModel
SettingsView -down-> SettingsViewModel

InitialLoginViewModel -down--> UserRepository
InitialLoginViewModel -down--> PetRepository

HomeViewModel -down> GoalRepository
HomeViewModel -down> UserRepository

SettingsViewModel -down-> UserRepository


PetRepository --down> PetDAO
UserRepository --down> UserDAO
GoalRepository --down> GoalDAO

PetDAO -down-> Pet
UserDAO -down-> User
GoalDAO -down-> Goal
@enduml